# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/self_learning/fir_test/fir_test.srcs/sources_1/ip/dds_compiler_5M/dds_compiler_5M.xci
# IP: The module: 'dds_compiler_5M' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/self_learning/fir_test/fir_test.srcs/sources_1/ip/dds_compiler_5M/dds_compiler_5M_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_compiler_5M'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/self_learning/fir_test/fir_test.srcs/sources_1/ip/dds_compiler_5M/dds_compiler_5M.xci
# IP: The module: 'dds_compiler_5M' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/self_learning/fir_test/fir_test.srcs/sources_1/ip/dds_compiler_5M/dds_compiler_5M_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_compiler_5M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
